version: "3.8"

services:
    go:
        image: golang
        working_dir: /go/src/app
        command: "go run main.go"
        ports:
            - 8080:8080
        volumes: 
            - ".:/go/src/app"